import { InvoiceBodyType, InvoicePaymentType, InvoiceType } from './addInvoceData';

export type CreateAddInvoiceRequestBodyType = {
  id: number;
  originInvoiceId: string;
  companyId: number;
  customerId: number;
  parentId: number;
  childId: number;
  taxid: string;
  orderDate: string;
  registerDate: string;
  inty: number;
  inno: string;
  irtaxid: string;
  inp: number;
  ins: number;
  tins: string;
  tob: number;
  bid: string;
  tinb: string;
  sbc: string;
  bpc: string;
  bbc: string;
  ft: number;
  bpn: string;
  scln: string;
  scc: string;
  crn: string;
  billid: string;
  tprdis: number;
  tdis: number;
  tadis: number;
  tvam: number;
  todam: number;
  tbill: number;
  setm: number;
  cap: number;
  insp: number;
  tvop: number;
  tax17: number;
  cdcn: string;
  cdcDate: string;
  tonw: number;
  torv: number;
  tocv: number;
  uid: string;
  referenceNumber: string;
  status: number;
  bodies: InvoiceBodyType[];
  payments: InvoicePaymentType[];
  postCustomerData: boolean;
};

export type CreateAddInvoiceResponseType = {
  statusCode: number;
  data: InvoiceType;
};
